FROM php-server:latest

RUN apt update \
    && apt install -y mariadb-client \
    && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install mysqli \
    && docker-php-ext-enable mysqli

COPY entrypoint.sh /usr/local/bin/drago-entrypoint.sh
RUN sed -i 's/\r$//' /usr/local/bin/drago-entrypoint.sh

ENTRYPOINT ["sh", "/usr/local/bin/drago-entrypoint.sh"]
CMD ["apache2-foreground"]
